"""
场景化技术术语词典
涵盖前端、后端、AI、DevOps、UI/UX 等细分领域
"""

EN_TO_ZH = {
    # ==================== 前端开发 (Frontend) ====================
    "react": "React 前端框架",
    "vue": "Vue 渐进式框架",
    "angular": "Angular 前端平台",
    "svelte": "Svelte 编译型框架",
    "jquery": "jQuery 库",
    "bootstrap": "Bootstrap 样式框架",
    "tailwind": "Tailwind CSS 原子化框架",
    "webpack": "Webpack 模块打包器",
    "vite": "Vite 构建工具",
    "esbuild": "esbuild 极速打包器",
    "babel": "Babel 转译器",
    "eslint": "ESLint 代码检查",
    "prettier": "Prettier 代码格式化",
    "axios": "Axios HTTP 请求库",
    "fetch api": "Fetch 网络请求接口",
    "swr": "SWR 数据请求库",
    "tanstack query": "TanStack 异步状态管理",
    "redux": "Redux 状态管理",
    "mobx": "MobX 响应式状态管理",
    "zustand": "Zustand 轻量状态管理",
    "pinia": "Pinia Vue 状态管理",
    "vuex": "Vuex 状态管理",
    "nextjs": "Next.js 全栈框架",
    "nuxtjs": "Nuxt.js Vue 服务端渲染框架",
    "gatsby": "Gatsby 静态站点生成",
    "dom": "文档对象模型",
    "virtual dom": "虚拟 DOM",
    "shadow dom": "影子 DOM",
    "reflow": "回流/重排",
    "repaint": "重绘",
    "critical rendering path": "关键渲染路径",
    "first contentful paint": "首次内容绘制",
    "largest contentful paint": "最大内容绘制",
    "time to interactive": "可交互时间",
    "cumulative layout shift": "累积布局偏移",
    "hydration": "注水/水合作用",
    "prerendering": "预渲染",
    "server side rendering": "服务端渲染",
    "static site generation": "静态站点生成",
    "incremental static regeneration": "增量静态再生",
    "event loop": "事件循环",
    "event bubbling": "事件冒泡",
    "event capturing": "事件捕获",
    "event delegation": "事件委托",
    "web worker": "网页工作线程",
    "service worker": "服务工作线程",
    "progressive web app": "渐进式网页应用",
    "web assembly": "网页汇编",
    "webgl": "网页图形库",
    "canvas": "画布",
    "svg": "可缩放矢量图形",
    "css grid": "CSS 网格布局",
    "flexbox": "弹性盒子布局",
    "media query": "媒体查询",
    "responsive design": "响应式设计",
    "mobile first": "移动优先",
    "pixel perfect": "像素级还原",
    "polyfill": "腻子脚本/垫片",
    "transpiling": "转译",

    # ==================== 后端开发 (Backend) ====================
    "spring boot": "Spring Boot 框架",
    "django": "Django 框架",
    "flask": "Flask 微框架",
    "fastapi": "FastAPI 异步框架",
    "express": "Express 框架",
    "nestjs": "NestJS 渐进式框架",
    "gin": "Gin 框架",
    "laravel": "Laravel 框架",
    "middleware": "中间件",
    "request interceptor": "请求拦截器",
    "response interceptor": "响应拦截器",
    "orm": "对象关系映射",
    "entity framework": "实体框架",
    "hibernate": "Hibernate 持久化框架",
    "mybatis": "MyBatis 持久层框架",
    "jpa": "Java 持久化接口",
    "migration": "数据库迁移",
    "seeding": "数据填充",
    "connection string": "连接字符串",
    "jdbc": "Java 数据库连接",
    "odbc": "开放数据库连接",
    "message queue": "消息队列",
    "rabbitmq": "RabbitMQ 消息中间件",
    "kafka": "Kafka 分布式流平台",
    "redis": "Redis 缓存数据库",
    "memcached": "Memcached 分布式缓存",
    "pub sub": "发布订阅模式",
    "event driven architecture": "事件驱动架构",
    "cron job": "定时任务",
    "batch processing": "批处理",
    "rate limiting": "限流",
    "throttling": "节流",
    "circuit breaker": "熔断器",
    "service mesh": "服务网格",
    "istio": "Istio 服务网格",
    "gateway": "网关",
    "reverse proxy": "反向代理",
    "nginx": "Nginx 服务器",
    "apache": "Apache 服务器",
    "tomcat": "Tomcat 容器",
    "jwt": "JSON 网络令牌",
    "oauth2": "OAuth2.0 授权协议",
    "openid connect": "OpenID 连接协议",
    "saml": "安全断言标记语言",
    "single sign on": "单点登录",
    "multi factor authentication": "多因素认证",
    "role based access control": "基于角色的访问控制",
    "microservices": "微服务架构",
    "monolith": "单体架构",
    "serverless": "无服务器架构",
    "faas": "函数即服务",
    "baas": "后端即服务",
    "webhook": "网络钩子",
    "idempotency": "幂等性",

    # ==================== AI / 机器学习 (AI / ML) ====================
    "artificial intelligence": "人工智能",
    "machine learning": "机器学习",
    "deep learning": "深度学习",
    "neural network": "神经网络",
    "convolutional neural network": "卷积神经网络",
    "recurrent neural network": "循环神经网络",
    "transformer": "Transformer 架构",
    "attention mechanism": "注意力机制",
    "self attention": "自注意力",
    "large language model": "大语言模型",
    "generative pre trained transformer": "生成式预训练 Transformer",
    "fine tuning": "微调",
    "prompt engineering": "提示词工程",
    "retrieval augmented generation": "检索增强生成",
    "vector database": "向量数据库",
    "embedding": "嵌入向量",
    "tokenization": "分词/标记化",
    "hallucination": "幻觉/胡编乱造",
    "inference": "推理",
    "training": "训练",
    "epoch": "训练轮次",
    "batch size": "批次大小",
    "learning rate": "学习率",
    "gradient descent": "梯度下降",
    "stochastic gradient descent": "随机梯度下降",
    "backpropagation": "反向传播",
    "overfitting": "过拟合",
    "underfitting": "欠拟合",
    "regularization": "正则化",
    "dropout": "随机失活",
    "normalization": "归一化",
    "activation function": "激活函数",
    "relu": "线性整流函数",
    "softmax": "归一化指数函数",
    "loss function": "损失函数",
    "cross entropy": "交叉熵",
    "mean squared error": "均方误差",
    "natural language processing": "自然语言处理",
    "computer vision": "计算机视觉",
    "object detection": "目标检测",
    "image segmentation": "图像分割",
    "optical character recognition": "光学字符识别",
    "sentiment analysis": "情感分析",
    "named entity recognition": "命名实体识别",
    "reinforcement learning": "强化学习",
    "agent": "智能体",
    "environment": "环境",
    "reward": "奖励",
    "policy": "策略",
    "value function": "价值函数",
    "q learning": "Q 学习",
    "generative adversarial network": "生成对抗网络",
    "variational autoencoder": "变分自编码器",
    "diffusion model": "扩散模型",
    "stable diffusion": "稳定扩散模型",
    "latent space": "潜在空间",
    "feature extraction": "特征提取",
    "dimensionality reduction": "降维",
    "pca": "主成分分析",
    "t sne": "t 分布随机邻域嵌入",
    "ensemble learning": "集成学习",
    "random forest": "随机森林",
    "xgboost": "极端梯度提升",
    "lightgbm": "轻量梯度提升机",
    "catboost": "类别型特征提升",
    "hyperparameter tuning": "超参数调优",
    "grid search": "网格搜索",
    "bayesian optimization": "贝叶斯优化",
    "explainable ai": "可解释人工智能",

    # ==================== DevOps / 运维 ====================
    "continuous integration": "持续集成",
    "continuous deployment": "持续部署",
    "continuous delivery": "持续交付",
    "devops": "开发运维一体化",
    "gitops": "Git 运维",
    "infrastructure as code": "基础设施即代码",
    "terraform": "Terraform 资源编排",
    "ansible": "Ansible 自动化运维",
    "puppet": "Puppet 配置管理",
    "chef": "Chef 配置管理",
    "saltstack": "SaltStack 自动化引擎",
    "docker": "Docker 容器引擎",
    "container": "容器",
    "image": "镜像",
    "dockerfile": "Docker 构建文件",
    "docker compose": "Docker 编排工具",
    "kubernetes": "Kubernetes 容器编排",
    "k8s": "K8s 容器编排",
    "pod": "容器组",
    "deployment": "部署控制器",
    "statefulset": "有状态副本集",
    "daemonset": "守护进程集",
    "ingress": "入口控制器",
    "service": "服务",
    "configmap": "配置映射",
    "secret": "密钥对象",
    "helm": "Helm 包管理器",
    "persistent volume": "持久化卷",
    "persistent volume claim": "持久卷声明",
    "horizontal pod autoscaler": "水平自动扩缩容",
    "vertical pod autoscaler": "垂直自动扩缩容",
    "cluster": "集群",
    "node": "节点",
    "namespace": "命名空间",
    "service account": "服务账户",
    "jenkins": "Jenkins 持续集成工具",
    "gitlab ci": "GitLab 持续集成",
    "github actions": "GitHub 工作流自动化",
    "argocd": "ArgoCD 持续部署工具",
    "prometheus": "Prometheus 监控系统",
    "grafana": "Grafana 可视化面板",
    "elasticsearch": "Elasticsearch 搜索引擎",
    "logstash": "Logstash 日志收集",
    "kibana": "Kibana 数据可视化",
    "elk stack": "ELK 日志分析套件",
    "fluentd": "Fluentd 统一日志层",
    "jaeger": "Jaeger 分布式追踪",
    "zipkin": "Zipkin 链路追踪",
    "opentelemetry": "OpenTelemetry 可观测性框架",
    "slo": "服务水平目标",
    "sla": "服务水平协议",
    "sli": "服务水平指标",
    "error budget": "错误预算",
    "chaos engineering": "混沌工程",
    "blue green deployment": "蓝绿部署",
    "canary deployment": "金丝雀部署",
    "rolling update": "滚动更新",
    "rollback": "回滚",
    "immutable infrastructure": "不可变基础设施",
    "cloud native": "云原生",
    "aws": "亚马逊云服务",
    "ec2": "弹性计算云",
    "s3": "简单存储服务",
    "rds": "关系型数据库服务",
    "lambda": "无服务器函数计算",
    "azure": "微软云",
    "gcp": "谷歌云平台",

    # ==================== UI / UX 设计 ====================
    "user interface": "用户界面",
    "user experience": "用户体验",
    "interaction design": "交互设计",
    "visual design": "视觉设计",
    "wireframe": "线框图",
    "mockup": "视觉稿/模型",
    "prototype": "原型",
    "low fidelity": "低保真",
    "high fidelity": "高保真",
    "figma": "Figma 设计工具",
    "sketch": "Sketch 设计工具",
    "adobe xd": "Adobe XD 设计工具",
    "zeplin": "Zeplin 设计交付工具",
    "design system": "设计系统",
    "component library": "组件库",
    "style guide": "样式指南",
    "persona": "用户画像",
    "user journey": "用户旅程",
    "user flow": "用户流程图",
    "sitemap": "站点地图",
    "a b testing": "A/B 测试",
    "usability testing": "可用性测试",
    "heatmap": "热力图",
    "eye tracking": "眼动追踪",
    "accessibility": "无障碍访问",
    "wcag": "网页内容无障碍指南",
    "aria": "无障碍富互联网应用",
    "contrast ratio": "对比度",
    "typography": "排版",
    "kerning": "字距调整",
    "leading": "行距",
    "grid system": "网格系统",
    "breakpoint": "断点",
    "viewport": "视口",
    "call to action": "行动号召按钮",
    "above the fold": "首屏可见区域",
    "hero section": "主视觉区域",
    "footer": "页脚",
    "sidebar": "侧边栏",
    "modal": "模态框",
    "popover": "气泡卡片",
    "tooltip": "工具提示",
    "toast": "轻提示",
    "carousel": "轮播图",
    "accordion": "手风琴折叠面板",
    "breadcrumb": "面包屑导航",
    "pagination": "分页",
    "infinite scroll": "无限滚动",
    "lazy loading": "懒加载",
    "skeleton screen": "骨架屏",
    "dark mode": "深色模式",
    "glassmorphism": "毛玻璃效果",
    "neumorphism": "新拟态风格",
    "flat design": "扁平化设计",
    "skeuomorphism": "拟物化设计",
    "affordance": "可供性",
    "signifier": "示能符号",
    "feedback": "反馈",
    "constraints": "约束",
    "mental model": "心智模型",
    "hick's law": "希克法则",
    "fitts's law": "菲茨定律",
    "gestalt principles": "格式塔原理",
}