"""
技术术语词典 - 完整增强版
包含编程语言关键字、语法构造、异常处理、网络协议、IDE操作等
"""

EN_TO_ZH = {
    # ==================== 第一部分：编程语言核心关键字 ====================
    # 通用控制流
    "if": "条件语句",
    "else": "否则分支",
    "elif": "否则如果",
    "switch": "开关语句",
    "case": "分支情况",
    "default": "默认分支",
    "for": "循环语句",
    "while": "当循环",
    "do while": "先执行后判断循环",
    "break": "跳出循环",
    "continue": "继续下一次循环",
    "return": "返回",
    "yield": "生成/产出",
    "await": "等待异步结果",
    "async": "异步函数修饰",
    "goto": "无条件跳转",
    "try": "尝试执行",
    "catch": "捕获异常",
    "except": "异常捕获",
    "finally": "最终执行",
    "throw": "抛出异常",
    "raise": "引发异常",
    "assert": "断言",
    
    # 数据类型与修饰符 (强类型语言)
    "int": "整型",
    "integer": "整数类型",
    "float": "浮点型",
    "double": "双精度浮点型",
    "long": "长整型",
    "short": "短整型",
    "byte": "字节型",
    "char": "字符型",
    "string": "字符串",
    "bool": "布尔型",
    "boolean": "布尔值",
    "void": "无返回值/空类型",
    "null": "空值",
    "nil": "空指针/空值",
    "none": "空对象",
    "undefined": "未定义",
    "enum": "枚举类型",
    "struct": "结构体",
    "union": "共用体",
    "typedef": "类型定义",
    "typeof": "类型查询",
    "instanceof": "实例判断",
    "sizeof": "获取内存大小",
    
    # 访问修饰符 (OOP)
    "public": "公共访问",
    "private": "私有访问",
    "protected": "受保护访问",
    "internal": "内部访问",
    "static": "静态成员",
    "final": "最终/不可变",
    "const": "常量",
    "readonly": "只读",
    "abstract": "抽象类/方法",
    "virtual": "虚方法",
    "override": "重写",
    "sealed": "密封类",
    "interface": "接口",
    "implements": "实现接口",
    "extends": "继承/扩展",
    "super": "父类引用",
    "base": "基类引用",
    "this": "当前实例",
    "self": "自身引用",
    "new": "新建对象/隐藏成员",
    "delete": "删除/释放内存",
    "malloc": "内存分配",
    "free": "释放内存",
    "sizeof": "大小计算",
    
    # 逻辑与位运算
    "and": "逻辑与",
    "or": "逻辑或",
    "not": "逻辑非",
    "xor": "异或运算",
    "bitwise": "按位运算",
    "left shift": "左移",
    "right shift": "右移",
    "unsigned": "无符号",

    # ==================== 第二部分：编程范式与概念 ====================
    # 原有 + 新增
    "data structure": "数据结构",
    "binary tree": "二叉树",
    "linked list": "链表",
    "hash table": "哈希表",
    "binary search": "二分查找",
    "depth first search": "深度优先搜索",
    "breadth first search": "广度优先搜索",
    "dynamic programming": "动态规划",
    "greedy algorithm": "贪心算法",
    "graph": "图",
    "stack": "栈",
    "queue": "队列",
    "heap": "堆",
    "trie": "字典树/前缀树",
    "backtracking": "回溯算法",
    "divide and conquer": "分治法",
    "two pointers": "双指针",
    "sliding window": "滑动窗口",
    "time complexity": "时间复杂度",
    "space complexity": "空间复杂度",
    "big o notation": "大O表示法",
    "recursion": "递归",
    "iteration": "迭代",
    "memoization": "记忆化搜索",
    "topological sort": "拓扑排序",
    "shortest path": "最短路径",
    "minimum spanning tree": "最小生成树",
    
    # 编程思想
    "object oriented programming": "面向对象编程",
    "functional programming": "函数式编程",
    "procedural programming": "过程式编程",
    "declarative programming": "声明式编程",
    "imperative programming": "命令式编程",
    "reactive programming": "响应式编程",
    "aspect oriented programming": "面向切面编程",
    "generic programming": "泛型编程",
    "metaprogramming": "元编程",
    "dependency injection": "依赖注入",
    "inversion of control": "控制反转",
    "single responsibility principle": "单一职责原则",
    "open closed principle": "开闭原则",
    "liskov substitution": "里氏替换原则",
    "interface segregation": "接口隔离原则",
    "dependency inversion": "依赖倒置原则",
    "dry principle": "不要重复自己原则",
    "kiss principle": "保持简单原则",
    "yagni": "你不会需要它原则",
    
    # 并发与多线程
    "asynchronous": "异步",
    "concurrency": "并发",
    "parallelism": "并行",
    "multithreading": "多线程",
    "coroutine": "协程",
    "deadlock": "死锁",
    "livelock": "活锁",
    "starvation": "饥饿",
    "race condition": "竞态条件",
    "mutex": "互斥锁",
    "semaphore": "信号量",
    "spinlock": "自旋锁",
    "atomic operation": "原子操作",
    "thread safe": "线程安全",
    "thread pool": "线程池",
    "fiber": "纤程",
    "green thread": "绿色线程",
    "callback hell": "回调地狱",
    "promise": "承诺对象",
    "observable": "可观察对象",
    "stream": "流式数据",
    "backpressure": "背压机制",

    # ==================== 第三部分：异常与调试术语 ====================
    "exception": "异常",
    "error": "错误",
    "stack trace": "堆栈追踪",
    "stack overflow": "栈溢出",
    "null pointer exception": "空指针异常",
    "null reference": "空引用",
    "index out of bounds": "索引越界",
    "key error": "键错误",
    "type error": "类型错误",
    "value error": "值错误",
    "syntax error": "语法错误",
    "indentation error": "缩进错误",
    "name error": "名称未定义错误",
    "attribute error": "属性错误",
    "import error": "导入错误",
    "module not found": "模块未找到",
    "file not found": "文件未找到",
    "permission denied": "权限拒绝",
    "connection refused": "连接被拒绝",
    "timeout": "超时",
    "segmentation fault": "段错误",
    "core dump": "核心转储",
    "memory leak": "内存泄漏",
    "buffer overflow": "缓冲区溢出",
    "integer overflow": "整数溢出",
    "unhandled rejection": "未处理的拒绝",
    "panic": "恐慌/严重错误",
    "recover": "恢复",
    "debug": "调试",
    "breakpoint": "断点",
    "watchpoint": "监视点",
    "step into": "单步进入",
    "step over": "单步跳过",
    "step out": "单步跳出",
    "call stack": "调用栈",

    # ==================== 第四部分：开发环境与工具 ====================
    # IDE 与编辑器操作
    "integrated development environment": "集成开发环境",
    "intellisense": "智能感知",
    "autocompletion": "自动补全",
    "syntax highlighting": "语法高亮",
    "code folding": "代码折叠",
    "code lens": "代码透镜",
    "refactoring": "重构",
    "rename symbol": "重命名符号",
    "extract method": "提取方法",
    "extract variable": "提取变量",
    "inline variable": "内联变量",
    "go to definition": "转到定义",
    "go to implementation": "转到实现",
    "find references": "查找引用",
    "peek definition": "速览定义",
    "quick fix": "快速修复",
    "code snippet": "代码片段",
    "live template": "动态模板",
    "keymap": "快捷键映射",
    "workspace": "工作区",
    "project": "项目",
    "solution": "解决方案",
    "build": "构建",
    "rebuild": "重新构建",
    "clean": "清理",
    "compile": "编译",
    "transpile": "转译",
    "minify": "压缩/最小化",
    "uglify": "混淆压缩",
    "bundling": "打包",
    "tree shaking": "摇树优化",
    "hot reload": "热重载",
    "live reload": "实时重载",
    "source map": "源码映射",
    
    # 版本控制 (Git)
    "version control": "版本控制",
    "repository": "仓库",
    "clone": "克隆",
    "fork": "派生/复刻",
    "branch": "分支",
    "master": "主分支",
    "main": "主线分支",
    "feature branch": "特性分支",
    "hotfix": "热修复",
    "commit": "提交",
    "push": "推送",
    "pull": "拉取",
    "fetch": "获取",
    "merge": "合并",
    "rebase": "变基",
    "cherry pick": "遴选",
    "stash": "暂存",
    "pop": "弹出",
    "checkout": "检出",
    "reset": "重置",
    "revert": "撤销/回滚",
    "tag": "标签",
    "pull request": "拉取请求",
    "merge request": "合并请求",
    "code review": "代码审查",
    "conflict": "冲突",
    "resolve conflict": "解决冲突",
    "diff": "差异对比",
    "blame": "追溯责任人",
    "bisect": "二分查找问题提交",
    "hook": "钩子脚本",
    "submodule": "子模块",
    "gitignore": "忽略文件配置",
    "origin": "源远程仓库",
    "upstream": "上游仓库",
    "head": "头指针",
    "detached head": "分离头指针状态",
    "fast forward": "快进合并",
    "squash": "压缩合并",
    
    # 包管理器
    "package manager": "包管理器",
    "dependency": "依赖项",
    "dev dependency": "开发依赖",
    "peer dependency": "同伴依赖",
    "lock file": "锁定文件",
    "registry": "注册表/镜像源",
    "semver": "语义化版本",
    "major version": "主版本号",
    "minor version": "次版本号",
    "patch version": "修订版本号",
    "breaking change": "破坏性变更",
    "deprecated": "已弃用",
    "legacy": "遗留/旧版",

    # ==================== 第五部分：网络与协议 ====================
    "internet protocol": "互联网协议",
    "transmission control protocol": "传输控制协议",
    "user datagram protocol": "用户数据报协议",
    "hypertext transfer protocol": "超文本传输协议",
    "hypertext transfer protocol secure": "超文本传输安全协议",
    "websocket": "网络套接字",
    "server sent events": "服务器推送事件",
    "web real time communication": "网页实时通信",
    "file transfer protocol": "文件传输协议",
    "simple mail transfer protocol": "简单邮件传输协议",
    "post office protocol": "邮局协议",
    "domain name system": "域名系统",
    "dynamic host configuration protocol": "动态主机配置协议",
    "secure shell": "安全外壳协议",
    "transport layer security": "传输层安全协议",
    "secure sockets layer": "安全套接层",
    "internet control message protocol": "互联网控制报文协议",
    "address resolution protocol": "地址解析协议",
    "network address translation": "网络地址转换",
    "virtual private network": "虚拟专用网络",
    "proxy": "代理",
    "firewall": "防火墙",
    "load balancer": "负载均衡器",
    "content delivery network": "内容分发网络",
    "domain name": "域名",
    "subdomain": "子域名",
    "top level domain": "顶级域名",
    "fully qualified domain name": "完全限定域名",
    "uniform resource locator": "统一资源定位符",
    "uniform resource identifier": "统一资源标识符",
    "query string": "查询字符串",
    "payload": "负载数据",
    "endpoint": "端点",
    "restful api": "表述性状态传递接口",
    "graphql": "图形查询语言",
    "remote procedure call": "远程过程调用",
    "grpc": "gRPC 远程调用框架",
    "swagger": "接口文档工具",
    "openapi": "开放接口规范",
    "cors": "跨域资源共享",
    "csrf": "跨站请求伪造",
    "xss": "跨站脚本攻击",
    "sql injection": "SQL 注入攻击",
    "denial of service": "拒绝服务攻击",
    "distributed denial of service": "分布式拒绝服务攻击",
    "man in the middle": "中间人攻击",
    
    # HTTP 细节
    "request": "请求",
    "response": "响应",
    "header": "请求头/响应头",
    "body": "消息体",
    "cookie": "浏览器缓存凭证",
    "session": "会话",
    "token": "令牌",
    "json web token": "JSON 网络令牌",
    "oauth": "开放授权协议",
    "openid connect": "OpenID 连接协议",
    "saml": "安全断言标记语言",
    "status code": "状态码",
    "ok": "成功",
    "created": "已创建",
    "accepted": "已接受",
    "no content": "无内容",
    "moved permanently": "永久移动",
    "found": "临时移动",
    "bad request": "错误请求",
    "unauthorized": "未授权",
    "forbidden": "禁止访问",
    "not found": "未找到",
    "method not allowed": "方法不允许",
    "internal server error": "内部服务器错误",
    "bad gateway": "网关错误",
    "service unavailable": "服务不可用",
    "gateway timeout": "网关超时",

    # ==================== 第六部分：数据库与存储 ====================
    "database": "数据库",
    "relational database management system": "关系型数据库管理系统",
    "non relational": "非关系型",
    "structured query language": "结构化查询语言",
    "nosql": "非结构化查询语言",
    "table": "表",
    "row": "行/记录",
    "column": "列/字段",
    "primary key": "主键",
    "foreign key": "外键",
    "index": "索引",
    "unique key": "唯一键",
    "composite key": "复合键",
    "constraint": "约束",
    "schema": "模式/结构",
    "migration": "迁移",
    "seed": "种子数据",
    "transaction": "事务",
    "acid": "原子性、一致性、隔离性、持久性",
    "atomicity": "原子性",
    "consistency": "一致性",
    "isolation": "隔离性",
    "durability": "持久性",
    "begin transaction": "开始事务",
    "commit": "提交事务",
    "rollback": "回滚事务",
    "savepoint": "保存点",
    "isolation level": "隔离级别",
    "read uncommitted": "读未提交",
    "read committed": "读已提交",
    "repeatable read": "可重复读",
    "serializable": "串行化",
    "dirty read": "脏读",
    "non repeatable read": "不可重复读",
    "phantom read": "幻读",
    "lock": "锁",
    "row lock": "行级锁",
    "table lock": "表级锁",
    "optimistic lock": "乐观锁",
    "pessimistic lock": "悲观锁",
    "deadlock": "死锁",
    "sharding": "分片",
    "partition": "分区",
    "replication": "复制",
    "master slave": "主从架构",
    "master master": "主主架构",
    "quorum": "法定人数",
    "failover": "故障转移",
    "backup": "备份",
    "restore": "恢复",
    "snapshot": "快照",
    "write ahead log": "预写日志",
    "binlog": "二进制日志",
    "connection pool": "连接池",
    
    # SQL 关键字
    "select": "查询",
    "insert": "插入",
    "update": "更新",
    "delete": "删除",
    "truncate": "截断表",
    "drop": "删除结构",
    "create": "创建",
    "alter": "修改结构",
    "where": "条件筛选",
    "join": "连接查询",
    "inner join": "内连接",
    "left join": "左连接",
    "right join": "右连接",
    "full join": "全连接",
    "cross join": "交叉连接",
    "union": "并集",
    "union all": "并集（包含重复）",
    "intersect": "交集",
    "except": "差集",
    "except all": "差集（包含重复）",
	
	
}